version: "3.8"
services:
    postgresql:
        image: postgres:13.5
        restart: always
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=zaq1@WSX
            - POSTGRES_DB=test
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    postgres:
